SELECT
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    IF(FREEZER_YN IS NOT NULL,FREEZER_YN,'N') AS FREEZER_YN
FROM
    FOOD_WAREHOUSE
WHERE 
    ADDRESS like '%경기도%'
ORDER BY
   WAREHOUSE_ID
  