SELECT f.ID, n.FISH_NAME, f.LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE
WHERE (f.FISH_TYPE, f.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY f.ID;