SELECT
    BOOK_ID,
    IF(PUBLISHED_DATE = '0000-00-00', '0000-00-00', DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')) AS FORMATTED_DATE
FROM
    book
WHERE
    CATEGORY = '인문' AND YEAR(PUBLISHED_DATE) = 2021
ORDER BY
    PUBLISHED_DATE ASC;
