SELECT
  CASE
    WHEN d.skill_code & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
         AND d.skill_code & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
      THEN 'A'
    WHEN d.skill_code & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
      THEN 'B'
    WHEN d.skill_code & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
      THEN 'C'
  END AS GRADE,
  d.ID,
  d.EMAIL
FROM DEVELOPERS d
WHERE d.skill_code & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') > 0
   OR d.skill_code & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
ORDER BY GRADE ASC, d.ID ASC;